### ISSUE TITLE
Bug with 'colocalizes with' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/paint#15] opened 2016-04-20 15:32 UTC
Hello, 

In PAINT2.0-beta 15, trying to propagate a 'colocalizes' annotation crashes PAINT :( 
For example: In PTHR14625, try to propagate Nucleus. 

Thanks, Pascale

**Comment by selewis** [comment] 2016-04-28 21:38
I couldn't duplicate this. It would just as you'd expect. Did the dialog box show up? Can you send me the console output too.

**Comment by pgaudet** [comment] 2016-06-10 13:11
Hello, 

This happened again with PTHR11715. The pop up box does appeear, but then nothing happens when I try to click on continue (or check the 'CONTRIBUTES TO box). I have been waiting for over 3 hours. 

Here's the terminal window output, but it didn't seem to have output anything: 

M-200278:paint2.0-beta pascalegaudet$ sh launchpaint.sh
2016-06-09 11:15:07,444 INFO  (PaintYaml:45) Trying config found at: config/preferences.yaml
2016-06-09 11:15:07,550 INFO  (PaintYaml:50) Using config found at: config/preferences.yaml
2016-06-09 11:15:07,838 INFO  (PaintStartupTask:203) Loading Paint version 2.0-beta19
2016-06-09 11:15:20,220 INFO  (class:571) View #4, Garbage0, is a garbage view--destroying
2016-06-09 11:16:15,648 INFO  (LoginUtil:404) Logging in to Panther URL:  http://paintcuration.usc.edu
2016-06-09 11:16:26,131 INFO  (ParserWrapper:67) Start loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.owl
2016-06-09 11:25:03,515 INFO  (ParserWrapper:74) Finished loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.owl
2016-06-09 11:25:04,630 INFO  (Reasoner:117) ELK reasoner was created
2016-06-09 11:25:18,733 INFO  (LoggingStageExecutor:70) Loading of Axioms started
2016-06-09 11:25:18,876 INFO  (AbstractReasonerStage:161) Loading of Axioms using 2 workers
2016-06-09 11:25:38,600 WARN  (ChangeIndexingProcessor:66) ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000051>)
2016-06-09 11:25:51,606 INFO  (LoggingStageExecutor:103) Loading of Axioms took 32732 ms
2016-06-09 11:25:51,606 INFO  (LoggingStageExecutor:70) Property Saturation Initialization started
2016-06-09 11:25:51,621 INFO  (AbstractReasonerStage:161) Property Saturation Initialization using 2 workers
2016-06-09 11:25:51,624 INFO  (LoggingStageExecutor:103) Property Saturation Initialization took 6 ms
2016-06-09 11:25:51,624 INFO  (LoggingStageExecutor:70) Reflexive Property Computation started
2016-06-09 11:25:51,628 INFO  (AbstractReasonerStage:161) Reflexive Property Computation using 2 workers
2016-06-09 11:25:51,632 INFO  (LoggingStageExecutor:103) Reflexive Property Computation took 8 ms
2016-06-09 11:25:51,632 INFO  (LoggingStageExecutor:70) Object Property Hierarchy and Composition Computation started
2016-06-09 11:25:51,638 INFO  (AbstractReasonerStage:161) Object Property Hierarchy and Composition Computation using 2 workers
2016-06-09 11:25:51,658 INFO  (LoggingStageExecutor:103) Object Property Hierarchy and Composition Computation took 25 ms
2016-06-09 11:25:52,099 INFO  (LoggingStageExecutor:70) Context Initialization started
2016-06-09 11:25:52,100 INFO  (AbstractReasonerStage:161) Context Initialization using 2 workers
2016-06-09 11:25:52,103 INFO  (LoggingStageExecutor:103) Context Initialization took 3 ms
2016-06-09 11:25:52,103 INFO  (LoggingStageExecutor:70) Consistency Checking started
2016-06-09 11:25:52,113 INFO  (AbstractReasonerStage:161) Consistency Checking using 2 workers
2016-06-09 11:25:52,229 INFO  (LoggingStageExecutor:103) Consistency Checking took 125 ms
2016-06-09 11:25:52,229 INFO  (LoggingStageExecutor:70) Class Taxonomy Computation started
2016-06-09 11:25:52,243 INFO  (AbstractReasonerStage:161) Class Taxonomy Computation using 2 workers
2016-06-09 11:26:38,711 INFO  (LoggingStageExecutor:103) Class Taxonomy Computation took 46481 ms
2016-06-09 11:29:13,040 INFO  (IDmap:113) Identical Seq ID (UniProtKB:Q8ZHI7) for 2 different genes: ENSEMBL:YP_3603 ENSEMBL:y3293
2016-06-09 11:29:13,047 INFO  (DisplayTree:70) There are 267 nodes in the PTHR11715 tree

---
Thanks, Pascale

**Comment by cmungall** [comment] 2016-06-10 14:23
Thanks for posting the log output.

Most of that is logging from the OWLAPI and is all normal.

This comes from PAINT:
2016-06-09 11:29:13,040 INFO (IDmap:113) Identical Seq ID 
(UniProtKB:Q8ZHI7) for 2 different genes: ENSEMBL:YP_3603 ENSEMBL:y3293

I very much doubt it is the cause, but that is all I would have to go on 
without investigating a lot more deeply, I'm sure Suzi could figure it 
out quickly but she's not back until after next week.

**Comment by selewis** [comment] 2016-06-25 15:16
Yes, messages such as this: 
2016-06-09 11:29:13,040 INFO (IDmap:113) Identical Seq ID (UniProtKB:Q8ZHI7) for 2 different genes: ENSEMBL:YP_3603 ENSEMBL:y3293 

Are informational only. There are many cases with one uniprot ID mapping to multiple gene IDs, and similarly single gene IDs mapping to multiple UniProt IDs. Just the usual splits and merges of genes being out of phase across project. I output them simply because I was interested in how often this occurs and thinking that at some point it might be useful feedback to the gene annotators.

**Comment by selewis** [comment] 2016-06-25 15:20
Also I was unable to duplicate the problem.
I was able to annotate "contributes to" for glycine dehydrogenase in family PTHR 11715.
You got the dialog, clicked the check box, and hit continue, right?

mystified.

Using PAINT 2.0-beta19

**Comment by pgaudet** [comment] 2016-08-15 13:40
I get it ! You need to check *or not check) the 'contributes to' box, and hit 'enter'. For me the 'Continue' button is not working. So for usability, pls remove the button or activate it. 

Thanks, Pascale

**Comment by selewis** [comment] 2016-08-15 20:33
Do you know what version of Java you are running?

Try typing this on the command line:
java -version

**Comment by krchristie** [comment] 2016-08-26 22:26
I am seeing this problem also.

For family PTHR21524, I would like to propagate the term "cytoplasmic microtubules" with the colocalizes qualifier. When I drag the term to the root, the dialog box appears. PAINT doesn't seem fully crashed, as I can move this dialog window around, but the dialog box is unresponsive to any of these actions:
- checking the COLOCOLIZES button
- pressing the continue button
- clicking either the red x or green + buttons in the upper left corner to dismiss or expand the window
Since I can't do anything to make the box close, I have to quit PAINT.

Restarting PAINT and reloading this family duplicates the problem.

Below is info on Java version and output in console window.

thanks,

-Karen

Here is the info on my version of Java:
<pre>
bash-3.2$ java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
</pre>

Here is a portion of the stuff from the console window from the first time. I included some of the families before this one that I had also opened):
<pre>
2016-08-26 10:42:38,980 INFO  (DisplayTree:70) There are 15 nodes in the PTHR38608 tree
2016-08-26 10:42:43,376 INFO  (class:135) Retrieving experimental annotations from: http://golr.geneontology.org
2016-08-26 10:44:53,605 INFO  (GafRecorder:81) Wrote updated paint GAF to /Users/krc/Documents/PAINTcuration/GO-paint/PTHR38608/PTHR38608.gaf
2016-08-26 10:44:53,615 INFO  (GafRecorder:121) Wrote experimental evidence GAF to /Users/krc/Documents/PAINTcuration/GO-paint/PTHR38608/PTHR38608.exp
2016-08-26 10:52:20,109 INFO  (DisplayTree:70) There are 9 nodes in the PTHR40661 tree
2016-08-26 10:52:21,633 INFO  (class:135) Retrieving experimental annotations from: http://golr.geneontology.org
2016-08-26 10:59:57,066 INFO  (GafRecorder:81) Wrote updated paint GAF to /Users/krc/Documents/PAINTcuration/GO-paint/PTHR40661/PTHR40661.gaf
2016-08-26 10:59:57,075 INFO  (GafRecorder:121) Wrote experimental evidence GAF to /Users/krc/Documents/PAINTcuration/GO-paint/PTHR40661/PTHR40661.exp
2016-08-26 11:21:43,070 INFO  (IDmap:113) Identical Seq ID (UniProtKB:Q7PSE6) for 2 different genes: Gene:AGAP009389 Gene:AgaP_AGAP009389
2016-08-26 11:21:43,071 INFO  (DisplayTree:70) There are 15 nodes in the PTHR21524 tree
2016-08-26 11:21:46,419 INFO  (class:135) Retrieving experimental annotations from: http://golr.geneontology.org
Exception in thread "AWT-EventQueue-0" java.lang.reflect.UndeclaredThrowableException
          at com.sun.proxy.$Proxy0.handleReOpenApplication(Unknown Source)
          at com.apple.eawt._AppEventLegacyHandler$4.dispatchEvent(_AppEventLegacyHandler.java:126)
          at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:184)
          at com.apple.eawt._AppEventLegacyHandler.appReOpened(_AppEventLegacyHandler.java:124)
          at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:276)
          at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:273)
          at com.apple.eawt._AppEventHandler$_AppEventMultiplexor$1.run(_AppEventHandler.java:439)
          at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
          at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
          at java.awt.EventQueue.access$500(EventQueue.java:97)
          at java.awt.EventQueue$3.run(EventQueue.java:709)
          at java.awt.EventQueue$3.run(EventQueue.java:703)
          at java.security.AccessController.doPrivileged(Native Method)
          at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
          at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
          at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
          at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
          at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
          at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
          at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
          at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:497)
       at org.simplericity.macify.eawt.DefaultApplication$ApplicationListenerInvocationHandler.invoke(DefaultApplication.java:400)
       ... 21 more
Caused by: java.lang.AbstractMethodError: org.bbop.framework.AbstractApplicationStartupTask$MacApplicationSupport.handleReOpenApplication(Lorg/simplericity/macify/eawt/ApplicationEvent;)V
       ... 26 more
</pre>

Here is everything from the console window from killing PAINT with Ctrl-C within the terminal window and then relaunching PAINT onwards:
<pre>
^Cbash-3.2$ ./launchPAINT.sh 
2016-08-26 14:43:29,558 INFO  (PaintYaml:45) Trying config found at: config/preferences.yaml
2016-08-26 14:43:29,593 INFO  (PaintYaml:50) Using config found at: config/preferences.yaml
2016-08-26 14:43:29,666 INFO  (PaintStartupTask:203) Loading Paint version 2.21
2016-08-26 14:43:32,314 INFO  (class:571) View #4, Garbage0, is a garbage view--destroying
2016-08-26 14:43:53,666 INFO  (LoginUtil:404) Logging in to Panther URL:  http://paintcuration.usc.edu
2016-08-26 14:44:03,965 INFO  (ParserWrapper:67) Start loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.owl
Exception in thread "AWT-EventQueue-0" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.handleReOpenApplication(Unknown Source)
	at com.apple.eawt._AppEventLegacyHandler$4.dispatchEvent(_AppEventLegacyHandler.java:126)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:184)
	at com.apple.eawt._AppEventLegacyHandler.appReOpened(_AppEventLegacyHandler.java:124)
	at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:276)
	at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:273)
	at com.apple.eawt._AppEventHandler$_AppEventMultiplexor$1.run(_AppEventHandler.java:439)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.simplericity.macify.eawt.DefaultApplication$ApplicationListenerInvocationHandler.invoke(DefaultApplication.java:400)
	... 21 more
Caused by: java.lang.AbstractMethodError: org.bbop.framework.AbstractApplicationStartupTask$MacApplicationSupport.handleReOpenApplication(Lorg/simplericity/macify/eawt/ApplicationEvent;)V
	... 26 more
Exception in thread "AWT-EventQueue-0" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.handleReOpenApplication(Unknown Source)
	at com.apple.eawt._AppEventLegacyHandler$4.dispatchEvent(_AppEventLegacyHandler.java:126)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:184)
	at com.apple.eawt._AppEventLegacyHandler.appReOpened(_AppEventLegacyHandler.java:124)
	at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:276)
	at com.apple.eawt._AppEventHandler$_AppReOpenedDispatcher.performOnListener(_AppEventHandler.java:273)
	at com.apple.eawt._AppEventHandler$_AppEventMultiplexor$1.run(_AppEventHandler.java:439)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.simplericity.macify.eawt.DefaultApplication$ApplicationListenerInvocationHandler.invoke(DefaultApplication.java:400)
	... 21 more
Caused by: java.lang.AbstractMethodError: org.bbop.framework.AbstractApplicationStartupTask$MacApplicationSupport.handleReOpenApplication(Lorg/simplericity/macify/eawt/ApplicationEvent;)V
	... 26 more
2016-08-26 14:51:50,145 INFO  (ParserWrapper:74) Finished loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.owl
2016-08-26 14:51:50,455 INFO  (Reasoner:117) ELK reasoner was created
2016-08-26 14:51:56,833 INFO  (LoggingStageExecutor:70) Loading of Axioms started
2016-08-26 14:51:56,847 INFO  (AbstractReasonerStage:161) Loading of Axioms using 8 workers
2016-08-26 14:51:57,530 WARN  (ChangeIndexingProcessor:66) ELK does not support SymmetricObjectProperty. Axiom ignored:
SymmetricObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000050>)
2016-08-26 14:51:58,018 WARN  (ChangeIndexingProcessor:66) ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000051>)
2016-08-26 14:52:01,108 INFO  (LoggingStageExecutor:103) Loading of Axioms took 4264 ms
2016-08-26 14:52:01,109 INFO  (LoggingStageExecutor:70) Property Saturation Initialization started
2016-08-26 14:52:01,110 INFO  (AbstractReasonerStage:161) Property Saturation Initialization using 8 workers
2016-08-26 14:52:01,111 INFO  (LoggingStageExecutor:103) Property Saturation Initialization took 1 ms
2016-08-26 14:52:01,111 INFO  (LoggingStageExecutor:70) Reflexive Property Computation started
2016-08-26 14:52:01,114 INFO  (AbstractReasonerStage:161) Reflexive Property Computation using 8 workers
2016-08-26 14:52:01,116 INFO  (LoggingStageExecutor:103) Reflexive Property Computation took 5 ms
2016-08-26 14:52:01,116 INFO  (LoggingStageExecutor:70) Object Property Hierarchy and Composition Computation started
2016-08-26 14:52:01,119 INFO  (AbstractReasonerStage:161) Object Property Hierarchy and Composition Computation using 8 workers
2016-08-26 14:52:01,124 INFO  (LoggingStageExecutor:103) Object Property Hierarchy and Composition Computation took 7 ms
2016-08-26 14:52:01,124 INFO  (LoggingStageExecutor:70) Context Initialization started
2016-08-26 14:52:01,125 INFO  (AbstractReasonerStage:161) Context Initialization using 8 workers
2016-08-26 14:52:01,128 INFO  (LoggingStageExecutor:103) Context Initialization took 2 ms
2016-08-26 14:52:01,128 INFO  (LoggingStageExecutor:70) Consistency Checking started
2016-08-26 14:52:01,132 INFO  (AbstractReasonerStage:161) Consistency Checking using 8 workers
2016-08-26 14:52:01,212 INFO  (LoggingStageExecutor:103) Consistency Checking took 83 ms
2016-08-26 14:52:01,212 INFO  (LoggingStageExecutor:70) Class Taxonomy Computation started
2016-08-26 14:52:01,217 INFO  (AbstractReasonerStage:161) Class Taxonomy Computation using 8 workers
2016-08-26 14:52:08,851 INFO  (LoggingStageExecutor:103) Class Taxonomy Computation took 7639 ms
2016-08-26 14:53:50,637 INFO  (IDmap:113) Identical Seq ID (UniProtKB:Q7PSE6) for 2 different genes: Gene:AGAP009389 Gene:AgaP_AGAP009389
2016-08-26 14:53:50,639 INFO  (DisplayTree:70) There are 15 nodes in the PTHR21524 tree
2016-08-26 14:53:52,878 INFO  (class:135) Retrieving experimental annotations from: http://golr.geneontology.org
</pre>

**Comment by selewis** [comment] 2016-08-29 20:36
We changed/updated the layout manager library (macify) and I'm guessing
that is the problem. Will need to either revert or find a third
alternative. Not a super quick fix since it takes some research.

**Comment by krchristie** [comment] 2016-10-18 21:35
This problem with the popup menus being non-functional and impossible to dismiss also occurs with the "evolutionary loss" popup. 

![20161018-evolosspopup](https://cloud.githubusercontent.com/assets/10533218/19497192/12dd7348-9540-11e6-833b-592153aa33ea.jpg)

I understand that this is a super quick fix, but it is super annoying. I keep losing work because I've done several propagations in quick sucession without saving and get then get one of these popups which effectively renders PAINT non-functional as I have to force quit it and repeat what I've just done.

**Comment by cmungall** [comment] 2016-10-27 20:22
I have changed the label on this ticket from 'question' to 'bug'. And because @krchristie was losing work I added a label 'affects usability'.

**Comment by pgaudet** [comment] 2016-10-28 08:06
I think there is a work around for this bug: for me when I try to *click*
on continue, then PAINT freezes. However when I hit *enter* then it works
fine.

Pascale

**Comment by krchristie** [comment] 2016-11-01 03:59
Thanks for that info Pascale. Hitting 'enter' is a work around for at least not losing work.

However, the fact that these pop-ups are  non-functional in terms of being able to propagate a qualifier since ticking the box does not work means that there are some propagations that are impossible to make since it is impossible to select the qualifier.

-Karen

**Comment by selewis** [comment] 2016-11-23 00:04
I think this is related to this bug report: https://bugs.openjdk.java.net/browse/JDK-8139393
Basically the fact that the dialog is called from the drop function (which means the drop class has control of the mouse) it isn't letting go of mouse control for the dialog box to hear about.

It is java version dependent, but in the meantime I can implement the fix they recommend and see if that works. Can I ask you to test it please when I have it ready.

-S

**Comment by krchristie** [comment] 2016-11-23 16:25
I'll be happy to Suzi, just let me know.

-K

**Comment by selewis** [comment] 2016-12-08 05:27
I've made another attempt at a fix for this. Give try to v2.28b and see if I've managed to work around it.

**Comment by krchristie** [comment] 2016-12-08 23:31
v2.28b did not fix this for me.


v2.28c does fix the dialog box issue for me! 

FYI: I notice that this version seems to make my computer run quite loudly, i.e. activates the fan.
I also turned on "Activity Monitor" and watched the CPU load, and it is noticeably high in a way that correlates with v2.28c, especially after doing some propagations (launched, did some propagations, and quit 3 times). I didn't see this with v2.28a (only tested 1 time today, though I don't remember hearing the fan kick so regularly with previous versions of PAINT-2. This might not be avoidable based on the way you fixed the dialog box, but I thought I'd mention it. 

Also, v2.28c just has 2.28 in the title bar once it's launched. I know you've been trying to turn this around quickly, but it's super helpful to have that when I'm comparing different versions, so just wanted to point it out so it gets on your list to update for the next version.

Thanks!!

-Karen

**Comment by selewis** [comment] 2016-12-09 19:08
So happy that the dialog box issue is fixed (whew).

In my memory it's always been 'noisy' when initially loading during the
allocation of memory, so I don't think this is new. It should quiet down
post-loading.

I'll take a look at the title bar thing and make a v2.29 release.

**Closed** 2016-12-09 19:27 UTC
Labels: affects usability, bug

**Comment by krchristie** [comment] 2016-12-09 21:45
2.28c isn't any noisier than previous versions during initial loading. It's after a propagation that popped up the qualifier dialog box. But more of an FYI observation than anything else. Certainly the qualifier box works. I didn't actually check the taxon popup...

Thanks for fixing it!!!
